### ISSUE TITLE
Share configuration

### ISSUE THREAD

**Issue by edenhaus** [dckiller51/lovelace-body-miscale-card#14]
Hi @dckiller51,

thanks for the nice card :)
Can you please share the config of the card in the image below?
I get only bars and I like the one in the screenshot :)

![Configuration card](https://raw.githubusercontent.com/dckiller51/lovelace-body-miscale-card/master/examples/card-configuration.png)

**Comment by dckiller51** [comment]
This was before the update with the bars. I will look tonight to add a switch to activate or deactivate it.

**Comment by dckiller51** [comment]
> Hi @dckiller51,
> 
> thanks for the nice card :) Can you please share the config of the card in the image below? I get only bars and I like the one in the screenshot :)
> 
> ![Configuration card](https://raw.githubusercontent.com/dckiller51/lovelace-body-miscale-card/master/examples/card-configuration.png)

Until I find a real solution, you will find below a workaround.

```
body:
  bmi:
    severity:
      - from: 0
        to: 10000
        color: transparent
  visceral_fat:
    severity:
      - from: 0
        to: 10000
        color: transparent
  body_fat:
    severity:
      - from: 0
        to: 10000
        color: transparent
  protein:
    severity:
      - from: 0
        to: 10000
        color: transparent
  water:
    severity:
      - from: 0
        to: 10000
        color: transparent
  muscle_mass:
    severity:
      - from: 0
        to: 10000
        color: transparent
  bone_mass:
    severity:
      - from: 0
        to: 10000
        color: transparent
  weight:
    severity:
      - from: 0
        to: 10000
        color: transparent
  ideal:
    severity:
      - from: 0
        to: 10000
        color: transparent
  basal_metabolism:
    severity:
      - from: 0
        to: 10000
        color: transparent
  body_type:
    severity:
      - from: 0
        to: 10000
        color: transparent
  metabolic_age:
    severity:
      - from: 0
        to: 10000
        color: transparent
```
