### ISSUE TITLE
Card not working, only picture shown

### ISSUE THREAD

**Issue by TheFes** [dckiller51/lovelace-body-miscale-card#16]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
v 5.6.5

**Last working release (if known):**
none, newly installed today

**Browser and Operating System:**
Chrome 94.0.4606.61 (Official Build) (64-bit) (cohort: Stable) on Windows 10

**Description of problem:**
With the config below, I only get a nice picture of my scale, but no data.
Without the picture config, I only get a empty rectangle

```yaml
  - type: custom:body-miscale-card
    entity: bodymiscale.martijn
    image: /local/pictures/miscale2.jpg
    model: true
```

![image](https://user-images.githubusercontent.com/28803438/135816027-a6226f2d-48ab-4b20-855d-6155fae24221.png)

The entity works fine:
![image](https://user-images.githubusercontent.com/28803438/135816713-4f41e336-c927-4d0a-8421-a893b2a251b5.png)

**Javascript errors shown in the web inspector (if applicable):**
None as far as I can see. Only related thing I see in the inspector is this:
![image](https://user-images.githubusercontent.com/28803438/135816624-36d7e9ae-7801-4d15-b75a-fd434a0048dd.png)
