### ISSUE TITLE
Fully hide the card header

### ISSUE THREAD

**Issue by etcho** [dckiller51/lovelace-body-miscale-card#48]
Is it possible to hide the entire attribute header? I mean not show the background image or any of the main attributes on the top. I was able to hide everything, but the block was still there, empty but still there. 

For me the header informations are useless and would be nice to show only the body of the card, saving some space on my dashboard.

If already is possible and I missed this feature, could you point me the configuration entry for that?

**Comment by posreg** [comment]
Hello, looking for the same option.
Did you find any solution yet?
Regards

**Comment by etcho** [comment]
@posreg not yet.

**Comment by dckiller51** [comment]
Hello, the easiest way is to use the bar-card. Here's an example

```
type: custom:bar-card
entities:
  - entity: sensor.aurelien_basal_metabolism
    direction: right
    height: 30px
    width: 100%
    positions:
      icon: outside
      indicator: outside
      name: inside
      minmax: 'off'
      value: inside
    max: 3000
    min: 0
    severity:
      - color: orangered
        from: 0
        to: 1530
      - color: green
        from: 1530.01
        to: Infinity
    target: 1530
  - entity: sensor.aurelien_bmi
    name: BMI
    direction: right
    height: 30px
    width: 100%
    positions:
      icon: outside
      indicator: outside
      name: inside
      minmax: 'off'
      value: inside
    max: 40
    min: 0
    severity:
      - color: blue
        from: 0
        to: 18.5
      - color: green
        from: 18.51
        to: 25
      - color: orange
        from: 25
        to: 28
      - color: orangered
        from: 28.01
        to: 32
      - color: red
        from: 32.01
        to: Infinity
    target: 21.75
```
