### ISSUE TITLE
Boutton séléction

### ISSUE THREAD

**Issue by Hydci** [dckiller51/lovelace-body-miscale-card#5]
Bonjour, 
Pour commencer merci pour le travail fourni l'intégration et le lovelace sont parfait.
J'ai une petite question concernant les bouton pour changer les infos de l'utilisateur j'ai lu tout les ticket et de ce que j'ai compris je devrais mettre les choses comme ça 
```
type: custom:body-miscale-card
entity: bodymiscale.giovanni
model: true
image: /local/miscale2.jpg
buttons:
  Giovanni:
    label: Giovanni
    show: true
  Melissa:
    label: Melissa
    show: true
```
j'aimerais s'avoir si je me trompe ou non car impossible de les afficher en vous remerciant d'avance

PS: je me suis permis d'écrire en français car il me semble que vous l'êtes.
