### ISSUE TITLE
Can't scroll to see all metrics

### ISSUE THREAD

**Issue by dulek** [dckiller51/lovelace-body-miscale-card#71]
![Image](https://github.com/user-attachments/assets/4e55d082-ad44-4a25-befd-abf73ea6b1e5)

As you can see this is the bottom of the card, yet there are still further metrics and their graphs that I'm unable to scroll to. My config is below, please note that the last visible item's title is "visceral fat".

```
type: custom:body-miscale-card
model: true
unit: false
theme: true
show_name: true
show_states: false
show_attributes: true
show_always_details: true
show_toolbar: true
show_body: true
show_buttons: false
attributes:
  impedance:
    key: impedance
    impedance_required: true
body:
  basal_metabolism: false
  bmi:
    key: bmi
    severity:
      - from: 12
        to: 18.5
        color: blue
        label: low
      - from: 18.5
        to: 25
        color: green
        label: normal
      - from: 25
        to: 30
        color: orange
        label: high
      - from: 30
        to: 36.5
        color: red
        label: very_high
    impedance_required: false
  bmi_label: false
  body_fat:
    key: body_fat
    severity:
      - from: 5
        to: 12
        color: blue
        label: very_low
      - from: 12
        to: 18
        color: royalblue
        label: low
      - from: 18
        to: 23
        color: green
        label: normal
      - from: 23
        to: 28
        color: orange
        label: increased
      - from: 28
        to: 35
        color: red
        label: high
    impedance_required: true
  body_type: false
  bone_mass:
    key: bone_mass
    severity:
      - from: 0
        to: 2
        color: red
        label: insufficient
      - from: 2
        to: 4.2
        color: green
        label: normal
      - from: 4.2
        to: 6.4
        color: blue
        label: good
    impedance_required: true
  ideal: false
  metabolic_age:
    key: metabolic_age
    impedance_required: true
  muscle_mass:
    key: muscle_mass
    severity:
      - from: 39.3
        to: 49.4
        color: red
        label: insufficient
      - from: 49.4
        to: 59.5
        color: green
        label: normal
      - from: 59.5
        to: 69.6
        color: blue
        label: good
    impedance_required: true
  protein:
    key: protein
    severity:
      - from: 11
        to: 16
        color: red
        label: insufficient
      - from: 16
        to: 20
        color: green
        label: normal
      - from: 20
        to: 24
        color: blue
        label: good
    impedance_required: true
  visceral_fat:
    key: visceral_fat
    severity:
      - from: 5
        to: 10
        color: green
        label: normal
      - from: 10
        to: 15
        color: orange
        label: high
      - from: 15
        to: 20
        color: red
        label: very_high
    impedance_required: false
  water:
    key: water
    severity:
      - from: 45
        to: 55
        color: red
        label: insufficient
      - from: 55
        to: 65.1
        color: green
        label: normal
      - from: 65.1
        to: 75
        color: blue
        label: good
    impedance_required: true
  weight: false
entity: bodymiscale.michal
image: /local/images/miscale2.jpg
icons_body: /local/images/bodyscoreIcon
```
