### ISSUE TITLE
Breaking out additional info into own entities?

### ISSUE THREAD

**Issue by Stooovie** [dckiller51/lovelace-body-miscale-card#8]
Hi, thanks for the component. How would I break out the individual measurements such as Body fat, Visceral fat or BMI into their own entities so I can track them over time with things like Grafana? Thank you!

**Comment by SmarterHomeLife** [comment]
Hi, I'd be keen for this information as well.  Thanks!

**Comment by dckiller51** [comment]
The easiest way is to create a sensor template. One sensor per attibute
exemple:

```
- platform: template
  sensors:
    test_bmi:
      friendly_name: "Test BMI"
      value_template: >
        {{ state_attr('bodymiscale.test', 'bmi') }}
```
test_bmi = name sensor (sensor.test_bmi) (sensor.test_water).......
value_template = replace bmi for attribute (water, visceral_fat....) {{ state_attr('bodymiscale.test', 'bmi') }}

**Comment by SmarterHomeLife** [comment]
Thanks very much! I'll give that a go tonight.

**Comment by alinelena** [comment]
I am a little bit confused on this one... this is an HA config, .test i the name of the esphome integration?

**Comment by alinelena** [comment]
ok got it.. here is small bash script to generate sensors for all the attributes.

```bash
#!/usr/bin/env bash

user=$1

attr=(bmi basal_metabolism visceral_fat ideal bmi_label impedance lean_body_mass body_fat water bone_mass muscle_mass fat_mass_to_lose fat_mass_to_gain protein body_type body_score metabolic_age)
echo "- platform: template"
echo "  sensors:"
for a in ${attr[*]}; do 
echo "    ${a}_$user:
      friendly_name: \"${user^}'s ${a/_/ }\"
      value_template: >
        {{ state_attr('bodymiscale.$user', '$a') }}"
done
```

**Comment by alinelena** [comment]
above example is fine, if you want to use platform template..
if one wants to use template: integration things are slightly different

```
- sensor:
  - name: "metabolic age alin"
    unit_of_measurement: "years"
    state: >
      {{ state_attr('bodymiscale.alin', 'metabolic_age') }}
    state_class: measurement

```

i assumed in configuration.yaml one has

```
template: !include templates.yaml
```

a script to generate all for a user

```bash
#!/usr/bin/env bash

user=$1

attr=(bmi basal_metabolism visceral_fat ideal bmi_label lean_body_mass body_fat water bone_mass muscle_mass fat_mass_to_lose fat_mass_to_gain protein body_type body_score metabolic_age)
units=(No kcal No kg No kg % % kg kg kg kg % No No years)
i=0
for a in ${attr[*]}; do 
echo "- sensor:
  - name: \"${a/_/ } $user\""
echo "    unit_of_measurement: \"${units[i]}\""
echo "    state: >
      {{ state_attr('bodymiscale.$user', '$a') }}
    state_class: measurement"
((i++))          
done
```

this approach shall make sensors available in statistics for HA.
note the weight and impedance for a user are not. a cheap solution will be to reexport them by adding them to the list. probably this is nicer to be set at esphome level for these too... digging it
